"""
evaluate.py
===========
Loads trained checkpoints, computes final test-set metrics, and writes a
plain-language comparison report to results/comparison_report.md.

Usage
-----
    python -m src.evaluate [--device cpu|cuda|auto]

Requires:
  - results/checkpoints/vit.pth
  - results/checkpoints/cnn.pth
  - results/vit_history.json
  - results/cnn_history.json

(All generated by src/train.py)
"""

import argparse
import json
import os
import time

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
import torchvision
import torchvision.transforms as T
from tqdm import tqdm

from src.vit import build_small_vit
from src.cnn_baseline import CNNBaseline


CIFAR10_MEAN = (0.4914, 0.4822, 0.4465)
CIFAR10_STD  = (0.2470, 0.2435, 0.2616)

CIFAR10_CLASSES = [
    "airplane", "automobile", "bird", "cat", "deer",
    "dog", "frog", "horse", "ship", "truck",
]


def get_test_loader(batch_size: int = 256):
    tf = T.Compose([
        T.ToTensor(),
        T.Normalize(CIFAR10_MEAN, CIFAR10_STD),
    ])
    ds = torchvision.datasets.CIFAR10(root="data", train=False, download=True, transform=tf)
    return DataLoader(ds, batch_size=batch_size, shuffle=False, num_workers=2)


@torch.no_grad()
def evaluate_model(model, loader, device):
    """Returns (accuracy, avg_loss, inference_time_per_image_ms)."""
    model.eval()
    criterion = nn.CrossEntropyLoss()

    correct = 0
    total = 0
    total_loss = 0.0

    start = time.time()
    for images, labels in tqdm(loader, desc="Evaluating", leave=False):
        images, labels = images.to(device), labels.to(device)
        logits = model(images)
        loss = criterion(logits, labels)
        total_loss += loss.item() * images.size(0)
        correct += (logits.argmax(dim=1) == labels).sum().item()
        total += images.size(0)
    elapsed = time.time() - start

    accuracy = correct / total
    avg_loss = total_loss / total
    ms_per_image = (elapsed / total) * 1000.0
    return accuracy, avg_loss, ms_per_image


def format_time(seconds: float) -> str:
    if seconds < 60:
        return f"{seconds:.1f}s"
    return f"{seconds/60:.1f}min ({seconds:.0f}s)"


def write_report(vit_acc, cnn_acc, vit_loss, cnn_loss,
                 vit_params, cnn_params,
                 vit_history, cnn_history,
                 vit_ms, cnn_ms,
                 save_path="results/comparison_report.md"):

    vit_train_time = format_time(vit_history.get("training_time_seconds", 0))
    cnn_train_time = format_time(cnn_history.get("training_time_seconds", 0))

    best_vit_val = max(vit_history["val_acc"])
    best_cnn_val = max(cnn_history["val_acc"])
    epochs = len(vit_history["train_loss"])

    winner = "ViT" if vit_acc > cnn_acc else "CNN"
    margin = abs(vit_acc - cnn_acc) * 100

    # ── Qualitative interpretation ────────────────────────────────────────────
    if cnn_acc > vit_acc + 0.03:
        interpretation = f"""
The CNN outperforms the ViT by {margin:.1f} percentage points, which is the
**expected and well-documented outcome** at this scale. Here's why:

**Convolutional inductive bias**: A CNN's convolutional layers encode two
powerful priors about images *by construction*:
1. **Local spatial structure** — nearby pixels are more related than distant
   ones (the kernel looks at a neighbourhood, not the whole image).
2. **Translation equivariance** — the same feature detector applies everywhere
   in the image.

These priors are excellent starting points for image data. The CNN doesn't
have to *learn* that edges exist or that the top-left and bottom-right corners
of a 4×4 patch are related — its architecture assumes it.

**ViT must learn everything from data**: Self-attention is
permutation-invariant. With only positional embeddings to anchor spatial
relationships, the ViT must discover from the training data alone that nearby
patches are more relevant than distant ones. On CIFAR-10 (50,000 training
images, 32×32 pixels), there simply isn't enough data to overcome the CNN's
head start.

**What would change the outcome**:
- More data (original ViT paper used JFT-300M, a 300 million image dataset)
- Data augmentation strategies like CutMix, MixUp, or RandAugment
- A warmup-heavy learning rate schedule (ViTs are more sensitive to LR)
- A larger model with more layers and heads
- Pre-training on a larger dataset, then fine-tuning on CIFAR-10
""".strip()
    elif vit_acc > cnn_acc + 0.03:
        interpretation = f"""
The ViT outperforms the CNN by {margin:.1f} percentage points — a pleasant
surprise at this scale! This can happen with the right combination of
augmentation, regularisation (dropout), and training schedule.

Note that this doesn't contradict the general observation that ViTs need more
data than CNNs — it means the configuration here was particularly well-suited
to what the ViT can learn from CIFAR-10.
""".strip()
    else:
        interpretation = f"""
The ViT and CNN perform comparably (within {margin:.1f} pp). This is a
reasonable outcome: with careful tuning (appropriate augmentation, AdamW,
cosine LR decay, dropout), a small ViT can approach CNN performance even on
limited data. The CNN's inductive bias advantage is most visible when training
data is very scarce or the model is very large relative to the dataset.
""".strip()

    report = f"""# ViT vs CNN Baseline — CIFAR-10 Comparison Report

Generated after {epochs} training epochs on CIFAR-10.

---

## Final Test-Set Results

| Metric | ViT (from scratch) | CNN Baseline |
|---|---|---|
| **Test Accuracy** | **{vit_acc*100:.2f}%** | **{cnn_acc*100:.2f}%** |
| Test Loss | {vit_loss:.4f} | {cnn_loss:.4f} |
| Best Val Accuracy | {best_vit_val*100:.2f}% | {best_cnn_val*100:.2f}% |
| Trainable Parameters | {vit_params:,} | {cnn_params:,} |
| Total Training Time | {vit_train_time} | {cnn_train_time} |
| Inference Speed | {vit_ms:.3f} ms/image | {cnn_ms:.3f} ms/image |

---

## Why the Results Look This Way

{interpretation}

---

## Architecture Summary

### Vision Transformer (ViT)
- **Patch size**: 4×4 pixels → 64 patches per image
- **Sequence length**: 65 tokens (64 patches + 1 [CLS] token)
- **Embedding dimension**: 128
- **Attention heads**: 4 (head dimension: 32)
- **Transformer layers**: 6
- **MLP hidden dim**: 256
- **Positional encoding**: Learnable 1D embeddings
- **Classification**: [CLS] token → Linear(128, 10)

### CNN Baseline
- **Architecture**: 3 × [Conv-BN-ReLU × 2 + MaxPool] → 2-layer classifier
- **Channels**: 3 → 32 → 64 → 128
- **Spatial progression**: 32×32 → 16×16 → 8×8 → 4×4
- **Classifier input**: 128 × 4 × 4 = 2048 features
- **Regularisation**: Dropout(0.3) + BatchNorm

---

## Key Takeaways

1. **ViTs are not universally better** — they require significantly more data
   than CNNs to overcome their lack of spatial inductive bias. At CIFAR-10
   scale, this is a real disadvantage.

2. **The architecture is still fascinating**: Even an underperforming ViT
   produces interpretable attention maps (see `results/attention_visualizations/`)
   that show what the model learned to focus on — something CNNs don't offer
   as directly.

3. **The comparison is the point**: The goal of this project is not to squeeze
   out maximum CIFAR-10 accuracy — it's to genuinely understand how
   self-attention works as an image-processing mechanism, and to see concretely
   why ViTs behave differently from CNNs at different scales.

4. **Scaling changes everything**: At ImageNet scale or larger, the story
   reverses — ViTs can match or exceed CNNs. Getting there from this codebase
   would require more data, larger models, and significantly more compute.

---

*Report generated by `src/evaluate.py`.*
"""

    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    with open(save_path, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"\nComparison report saved → {save_path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--device", type=str, default="auto")
    args = parser.parse_args()

    device = torch.device(
        "cuda" if (args.device == "auto" and torch.cuda.is_available()) else
        "cpu" if args.device == "auto" else args.device
    )
    print(f"Device: {device}")

    # Load training histories
    with open("results/vit_history.json") as f:
        vit_history = json.load(f)
    with open("results/cnn_history.json") as f:
        cnn_history = json.load(f)

    test_loader = get_test_loader()

    # ViT
    vit = build_small_vit().to(device)
    vit.load_state_dict(torch.load("results/checkpoints/vit.pth", map_location=device))
    vit_acc, vit_loss, vit_ms = evaluate_model(vit, test_loader, device)
    print(f"ViT  — Test accuracy: {vit_acc*100:.2f}%  |  Loss: {vit_loss:.4f}")

    # CNN
    cnn = CNNBaseline().to(device)
    cnn.load_state_dict(torch.load("results/checkpoints/cnn.pth", map_location=device))
    cnn_acc, cnn_loss, cnn_ms = evaluate_model(cnn, test_loader, device)
    print(f"CNN  — Test accuracy: {cnn_acc*100:.2f}%  |  Loss: {cnn_loss:.4f}")

    write_report(
        vit_acc=vit_acc, cnn_acc=cnn_acc,
        vit_loss=vit_loss, cnn_loss=cnn_loss,
        vit_params=vit.count_parameters(),
        cnn_params=cnn.count_parameters(),
        vit_history=vit_history,
        cnn_history=cnn_history,
        vit_ms=vit_ms, cnn_ms=cnn_ms,
    )


if __name__ == "__main__":
    main()
